### ISSUE TITLE
FakeQuit/FakeJoin Issue

### ISSUE THREAD

**Issue by brinabo** [mbax/VanishNoPacket#255]
Hi, I have all the permissions required (I use Permissions Bukkit) to do /vanish fakequit and /vanish fakejoin
but when I attempt to use the command it says "[Vanish] Access Denied" and it doesn't display the logging out message to the other players.
have any idea why not? I have vanish.\* in my specific permissions.
Thanks
I run bukkit 1.3 recommended build and here are my permissions:

[spoiler] users:
    brinaq:
        permissions:
            Sanzennin.Watchdog._: true
            multiverse.teleport.self.worldcreate
            vanish.fakeannounce: true
            vanish.effects._
            parties.allow.create
            nse.*
            weathercontrol.*
            log.*
            log.admin*
            chat.*
            vanish.*
        groups:
        - admin [/spoiler]

**Comment by OPUBGG** [comment]
9 Years later and this problem still exists! I am using VanishNoPacket on my server and when I use Fakequit or Fakejoin, it simply says "[Vanish]Access Denied". Has anyone found a solution for this problem or is it still a thing?
