### ISSUE TITLE
Enjin websites

### ISSUE THREAD

**Issue by Konsider** [mbax/VanishNoPacket#520]
Would it be possible to make it so that when vanished, a player is also hidden from Enjin websites. Currently they still show up on the online player module lists, making VanishNoPacket useless if someone is watching the website.

**Comment by MrKiller01** [comment]
What about the autoupdate possibility? http://www.kitteh.org is pointing to cats, ordinairy cats, so how does that complete in the plugin

**Comment by TheMolkaPL** [comment]
@MrKiller01 create a new issue, not comment the old one. Also @mbax [is not contributing to this project](https://github.com/mbax/VanishNoPacket/issues/627#issuecomment-92340734).

**Comment by mbax** [comment]
Bukkit died over a year ago, @MrKiller01
