### ISSUE TITLE
'secret' login url

### ISSUE THREAD

**Issue by khobbits** [mbax/VanishNoPacket#550]
Make it so when logging in through a certain url, the default vanish state is reversed.

Use case:
Staff could normally join to mc.myserver.com and they would be shown joining
Logging in via secretmc.myserver.com and they would join vanished and silently.

This would allow for connect vanish state to be set, without changing permissions.

PlayerLoginEvent - getHostname() - Gets the hostname that the player used to connect to the server, or blank if unknown

**Comment by mbax** [comment]
Lovely idea. Will consider if I do something like this for Sponge.
