### ISSUE TITLE
Rewrite hooks

### ISSUE THREAD

**Issue by mbax** [mbax/VanishNoPacket#591]
* Essentials
* Dynmap
* Disguisecraft

**Comment by remco1271** [comment]
I have added to EssentialsHooks.java:
if (hide == false){
            	if (this.plugin.getServer().getPluginManager().getPlugin("dynmap") != null){
            	essentials.getVanishedPlayers().remove(player.getName());
            	}
            	Debuggle.log("player " + player.getName() + " is not more vanish in essentials that don't let you see in dynmap");
            }

To make me visible on dynmap after not more vanished on the server.
To fix the bug with essentials and dynmap.

**Comment by EvilOlaf** [comment]
I don't get it. 
I vanish, and I am invisible on dynmap. Then I unvanish and I am visible on dynmap again. 
So what is the snap for?

**Comment by remco1271** [comment]
On my server i am not visible on dynmap and i don't have permissions for essentials vanish.

**Comment by EvilOlaf** [comment]
If you are using vanishnopacket the essentials version of vanish is inactive.

Btw. you know the permission node "vanish.hooks.dynmap.alwayshidden"?

**Comment by remco1271** [comment]
No I needed to use essentials vanish in console to turn the vanish in dynmap off.
/ev {user_name} off
but i dont have essentials.vanish permission

**Comment by EvilOlaf** [comment]
Ah okey, then never mind ;)
