### ISSUE TITLE
Vanish visibility issue

### ISSUE THREAD

**Issue by Vizitri** [mbax/VanishNoPacket#613]
All the staff have "vanish.see" but when anyone goes into vanish, we can't see them, and when they unvanish, we can't see them either. Unless we leave the players area and reenter. This is affecting our Moderator's ability to do their jobs. Any help would be greatly appreciated. :)

**Comment by Vizitri** [comment]
I tested it, and I didn't have the same error.

**Comment by Vizitri** [comment]
Whoops, I hit the wrong button, but I tested it, and I didn't have the same issue.

**Comment by mbax** [comment]
If you didn't have the same issue, it's a problem with Spigot. I've received a large number of complaints about visibility with the Spigot builds.
