### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by LordDWT** [mbax/VanishNoPacket#614]
Any way you could use the built-in scoreboard system instead of TagAPI?

**Comment by mbax** [comment]
I could have.

This feature was written prior to the scoreboard even existing. I'd consider updating VNP to allow that as an option but I'm not doing any further Bukkit work until Mojang clarifies their position on the matter. They've made, in my opinion, conflicting statements about Bukkit. Until they come up with a solid statement referencing those past statements in a way that explains whether or not its safe to continue, there won't be a VNP update.

**Comment by LordDWT** [comment]
Ya I know TagAPI was the only option before 1.8 and thought I would suggest the scoreboard to get rid of another plugin that's not needed anymore.
I understand your position and respect that also.
You do know that what spigot did was legal and you as a developer should be able to program against there version?.
There are many developers you could ask about this if you would like.  For example BigScary From GriefPrevention is very active and might be able to assist you.

Thanks for your reply and awesome plugin!

**Comment by mbax** [comment]
> You do know that what spigot did was legal and you as a developer should be able to program against there version?.

I'm not referring to the DMCA when I talk about legal situations. That said, I wouldn't want to use anything Spigot builds. They are hiding from the DMCA takedown, not complying. Additionally, [I have my personal reasons](http://www.reddit.com/r/admincraft/comments/1lgcpx/tagapi_prints_stack_trace_to_spigot_users_fooling/cbz1gno) for not wanting to work with those folks. I could write a substantial essay on why it should be avoided.

**Comment by bitfreeze** [comment]
Hey Vanishman, my support to you on that.
They should not use a fake response in getName ...
Free hugs

β

**Comment by mbax** [comment]
@bitfreeze I was more referring to my comment in the thread about their response to the situation. ;)

**Comment by bitfreeze** [comment]
Now now. I was referring to your source code, which I consider to be
completely plausible and right to criticize the incorrect report on what
server version you're running.

After all, that can lead to unexpected issues and everyone will invariably
point a finger and blame you first, while you fully support the "official"
CB only.

β
