### ISSUE TITLE
Unable to damage-out to players unless opped

### ISSUE THREAD

**Issue by PiLoT-** [mbax/VanishNoPacket#615]
after updating my server to a new build of spigot (yes i know theres issue there, but i dont think this is relevant)

/v t damage-out toggles but only op can deal damage. any advice?

**Comment by mbax** [comment]
What happens when you try out CraftBukkit (Not Spigot or Spigot's CraftBukkit, but actual CraftBukkit)

**Comment by PiLoT-** [comment]
i havent tried it, it could be a permission im missing?

**Comment by mbax** [comment]
Let me know when you try it.

**Comment by mbax** [comment]
Closing for lack of response. Feel free to reply with further information and we can continue right here.

**Comment by PiLoT-** [comment]
ok seemed to do same behaviour when i rolled back. so either vanish nodes have changed. or spigots updates have changed something. the nodes have been assigned correctly afaik but non opped mods and admins cant hurt players only mobs

**Comment by mbax** [comment]
Can you pastebin a server startup from that? :)

**Comment by PiLoT-** [comment]
http://pastebin.com/aTZd6ryD

**Comment by mbax** [comment]
I asked for CraftBukkit, not Spigot. Let me know how it goes when you test it on CraftBukkit.

**Comment by PiLoT-** [comment]
ah sorry

**Comment by PiLoT-** [comment]
struggling to find a stock crafbukkit to test on cause of DMCA

**Comment by mbax** [comment]
Well, this issue was never reported on CraftBukkit. So I stick to the assumption that it's a Spigot bug.
