### ISSUE TITLE
Effects - Config

### ISSUE THREAD

**Issue by Crafter213** [mbax/VanishNoPacket#616]
This is a nice plugin, but all the effects may seem useless.
Even if they are nice to see, please give the opportunity to disable every Effect.
Thanks! :D

**Comment by bitfreeze** [comment]
You have permission nodes for each effect. Set up your permissions, I'd say.

β

**Comment by mbax** [comment]
Every single effect is disabled by default. You, the server administrator, must explicitly grant the permission nodes for the effects in order for them to be 1) Used or 2) Toggled at all

Don't grant nodes you don't want! :)

**Comment by EvilOlaf** [comment]
If you are OP or have all permissions by adding * to your user or usergroup you have all effects.
It is recommended not to use * as permission, but if you want to keep it you can especially disable these effects by adding -vanish.effects.* to you or your group.

**Comment by mbax** [comment]
OP does not get the effects nodes, @EvilOlaf 

It's only by explicitly granting the permissions (Using a plugin which allows wildcarding and granting a wildcard that covers it counts).

**Comment by Crafter213** [comment]
Thank you :)
