### ISSUE TITLE
Cannot disable lightning effects. 

### ISSUE THREAD

**Issue by dodgybrothers** [mbax/VanishNoPacket#617]
Hi, I'm having issues disabling all the effects on my server, I've checked everything and it looks fine, yet the effects still occur when vanishing and unvanishing. 

Permissions File: http://pastebin.com/R4swQAFS
Config File: http://pastebin.com/PQYX2RvA

Cheers,

dodgybrothers

**Comment by mbax** [comment]
They're disabled by default. Don't grant them and you won't run into such troubles. ;)
