### ISSUE TITLE
Vanished player actions - bug

### ISSUE THREAD

**Issue by madtomic** [mbax/VanishNoPacket#618]
vanish players actions are block as long they are vanished.

If they turn off vanish.     - vanish.nointeract is no longer applied?

Can this be fix? So as long the vanished or not vanished player had this permission. They are not able to interact.

**Comment by mbax** [comment]
nointeract only applies while vanished. The purpose is to prevent invisible players from 1) being noticed by others or 2) accidentally disrupting things they shouldn't be while invisible

That's why it's vanish.nointeract,  not allthetime.nointeract  ;)

**Comment by madtomic** [comment]
I see. Can you make another plugin that blocks all the actions while vanished ? 😁

**Comment by madtomic** [comment]
Not vanished I meant

**Comment by mbax** [comment]
Sorry, but no. I'm not doing any further plugin work until Mojang/Microsoft clarifies their position on modding and won't be doing any Bukkit work until Mojang resolves the licensing mess they've apparently owned for nearly 3 years.

**Comment by madtomic** [comment]
ok, i understand. great plugin btw.

**Comment by gsand** [comment]
@madtomic disable those actions using worldguard.

**Comment by madtomic** [comment]
i don't like worldguard or worldedit. i can hack around it. :(
