### ISSUE TITLE
Vanished player can push entities 

### ISSUE THREAD

**Issue by madtomic** [mbax/VanishNoPacket#620]
as subject. Weird to see

**Comment by EvilOlaf** [comment]
And you are sure you gave the nointeract permission?

**Comment by madtomic** [comment]
i wouldn't report this bug if i wasn't sure. :)

**Comment by madtomic** [comment]
permissions:
    - vanish.joinvanished
    - vanish.silentquit
    - vanish.nopickup
    - vanish.nohunger
    - vanish.nointeract
    - vanish.nochat
    - vanish.preventdamage
    - vanish.nofollow
    - vanish.notrample

**Comment by EvilOlaf** [comment]
Hm can't reproduce. Using quite similar permission nodes.
How do you get vanished without 
```
vanish.vanish
```
node ?

**Comment by madtomic** [comment]
the player join with - vanish.joinvanished in group. no need to get out of vanish.

in this vanished state. they can go push a cow or any entities in the game.

**Comment by madtomic** [comment]
if you let for example guest to explore your world and don't want them to break or interact anything in the game. they can still go push entities around.

**Comment by EvilOlaf** [comment]
And you think solving this with vanish instead of modifyworld is a good idea? ^^

**Comment by madtomic** [comment]
i would use modifyworld for everything if this can already do these things. I want to know why while vanished. you can still push pigs around. LOL

**Comment by mbax** [comment]
Certain nudging isn't preventable with VanishNoPacket. Sorry! :)

**Comment by EvilOlaf** [comment]
As written usually you can't do that. Working pretty well for me :/

**Comment by madtomic** [comment]
thank you mbax. lol... nudging... :)
