### ISSUE TITLE
Rearranged Inventory

### ISSUE THREAD

**Issue by WMD17** [mbax/VanishNoPacket#622]
While vanished if you were to open a hopper or chest, your inventory may be rearranged and your armor removed. This does not happen all the time but has been occurring a lot recently. The bug is fixed if you were to relax back onto the server.

**Comment by mbax** [comment]
Server version please.

**Comment by WMD17** [comment]
1.8 Spigot

**Comment by mbax** [comment]
That's not a full version string, but either way: Can you test on CraftBukkit 1.7.10? Last actual CB release?

**Comment by WMD17** [comment]
[15:43:25 INFO]: This server is running CraftBukkit version git-Spigot-081dfa5-5e6c347 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Comment by mbax** [comment]
Then I can't help confirm if it's a VNP bug or not.
