### ISSUE TITLE
Stay vanished

### ISSUE THREAD

**Issue by iAmGuus** [mbax/VanishNoPacket#623]
When I join, I am always vanished. Is this a bug of the plugin or is it myself? I was wondering.
Btw, I am running Spigot 1.7.x & 1.8.x.

**Comment by EvilOlaf** [comment]
Check your permissions.

**Comment by mbax** [comment]
As EvilOlaf said, your permissions are the issue. Don't grant permission nodes that you don't understand or don't want! :)
