### ISSUE TITLE
3.19.1 - Lost inventory items when opening hopper (possibly other things too)

### ISSUE THREAD

**Issue by Zhro** [mbax/VanishNoPacket#625]
Latest Spigot 1.8.3
ProtocolLib build #103

Permissions:
+ vanish.standard

Vanish and right click on a hopper. It moves items in your inventory around.

Using /clear also doesn't work and bugs out the inventory completely until a relog.

**Comment by mbax** [comment]
VanishNoPacket is a Bukkit plugin.

1) Mojang has not clarified their position on the legality of Bukkit and modding. While they publicly stated on twitter that Bukkit has a 'special relationship' they very clearly denied that same relationship in the letter they sent Wolvereness which he quotes in his DMCA takedown. Their COO made several statements about the project which did not match up with reality, which is scary. I do not feel safe continuing work on Bukkit plugins until Mojang makes it explicitly clear that it's safe.

2) There has not been and will never be a 1.8 release of Bukkit or CraftBukkit. The only major Bukkit fork legally updated to 1.8 is Glowstone, which still lacks a lot of features so isn't yet worth updating to even if the first item in this list were resolved. The other updated fork is Spigot, which I refuse to support. Here's a short list of examples why:

* They spent substantial time insulting me and my fellow Bukkit developers
* The founder, md_5, regularly attacked me directly, out of some one-sided feud he created ([example](http://www.reddit.com/r/admincraft/comments/1lgcpx/tagapi_prints_stack_trace_to_spigot_users_fooling/cbz1gno))
* They spent a lot of time trying to convince the community they were doing the hard work of a Bukkit update, when they were just applying some patches on top of my hard work.
* They convinced the community to pay them a huge pile of money to fight the DMCA takedown they received, only to never actually file the counterclaim they said they would do.
* They are now ignoring the (apparently determined by the lawyers they paid to be valid, as they didn't issue a response) DMCA takedown, hiding their servers behind proxies.
