### ISSUE TITLE
Cannot use colours in fakejoin/quit

### ISSUE THREAD

**Issue by Eshonbel** [mbax/VanishNoPacket#626]
I want the fakejoin/quit to look the same as my normal essentials coloured join/quit, but it won't let me - it is all in yellow. I put it to use & colours, but, instead of showing the colours, it just shows the colour value (&6Eshonbel &5quit the game.)

**Comment by EvilOlaf** [comment]
https://github.com/mbax/VanishNoPacket/issues/611

**Comment by Eshonbel** [comment]
Aight, didn't know. Thank you.
