### ISSUE TITLE
Permissions on Spigot 1.8

### ISSUE THREAD

**Issue by icomputertinker** [mbax/VanishNoPacket#628]
Hi there!
I have a bit of a problem: Vanish is telling me "Access Denied" for most things, but not simply "/v"

I've looked through a few other threads, you told some to use /permcheck. I did that, it told me that I didn't have permission to use fakequit. I was using GroupManager at the time, and so I changed to bPermissions and reconfigured it all, made sure that the permissions were in order. bPermissions seems to work fine for everything except for VNP. 

Any help is appreciated.

**Comment by icomputertinker** [comment]
I see on some other tickets you have a canned spigot response, which is totally fine with me, but I don't think this is a spigot issue, I have a feeling that this is simply a version plugin issue. :( If you think that I should use a different plugin, just recommend one. :)

**Comment by TheMolkaPL** [comment]
Spigot 1.8 is not supported.

As @mbax said:
> VanishNoPacket is a Bukkit plugin.

> 1) Mojang has not clarified their position on the legality of Bukkit and modding. While they publicly stated on twitter that Bukkit has a 'special relationship' they very clearly denied that same relationship in the letter they sent Wolvereness which he quotes in his DMCA takedown. Their COO made several statements about the project which did not match up with reality, which is scary. I do not feel safe continuing work on Bukkit plugins until Mojang makes it explicitly clear that it's safe.

> 2) There has not been and will never be a 1.8 release of Bukkit or CraftBukkit. The only major Bukkit fork legally updated to 1.8 is Glowstone, which still lacks a lot of features so isn't yet worth updating to even if the first item in this list were resolved. The other updated fork is Spigot, which I refuse to support. Here's a short list of examples why:

> They spent substantial time insulting me and my fellow Bukkit developers
The founder, md_5, regularly attacked me directly, out of some one-sided feud he created (example)
They spent a lot of time trying to convince the community they were doing the hard work of a Bukkit update, when they were just applying some patches on top of my hard work.
They convinced the community to pay them a huge pile of money to fight the DMCA takedown they received, only to never actually file the counterclaim they said they would do.
They are now ignoring the (apparently determined by the lawyers they paid to be valid, as they didn't issue a response) DMCA takedown, hiding their servers behind proxies.

https://github.com/mbax/VanishNoPacket/issues/627#issuecomment-92340734
