### ISSUE TITLE
Fakeannounce not working (internal server error)

### ISSUE THREAD

**Issue by vNoctis** [mbax/VanishNoPacket#630]
Everytime fakeannounce should show up , chat prints "an internal server error occurred ecc.."
Why?
Here is the pastebin (read from bottom to top) http://pastebin.com/0RUntTE9

**Comment by mbax** [comment]
Looks like you're using a very old version of CraftBukkit.

**Comment by vNoctis** [comment]
I'm using 1.7.2 R03 build and I put VNP on the right version. 
The 3.19.1 of VNP works with that build, I saw.
Why then?

**Comment by mbax** [comment]
Perhaps try 3.18.10
