### ISSUE TITLE
Joining vanished and "access denied" with /v despite permissions being configured to the contrary.

### ISSUE THREAD

**Issue by Drift91** [mbax/VanishNoPacket#631]
http://i.imgur.com/bamYuMq.png

I noticed this after installing DynMap, however can not replicate it with just the two plugins alone.

Here's an archive of all my plugins: https://www.dropbox.com/s/hrjppz0t906ga1z/plugins.zip?dl=0

Here's my only permissions nodes that should affect VanishNoPacket in PEX:
    - vanish.op
    - vanish.standard
    - -vanish.*
    - '*'

**Comment by mbax** [comment]
Output of **version** command please. Also, please test without the * node or the negation of vanish.*
