### ISSUE TITLE
Remove essentials Invisability II upon join

### ISSUE THREAD

**Issue by Snipershotmaster** [mbax/VanishNoPacket#634]
I have given the correct (negated) permission to my admins but still goin with the Invisability II effect. yes i have disabled allow-silent-join-quit: to false..

**Comment by mbax** [comment]
There is no `allow-silent-join-quit` in VanishNoPacket, nor do I recall having an enchantment applied. Are you sure you're talking about this plugin?

**Comment by EvilOlaf** [comment]
Sounds like an Essentials issue...

**Comment by Snipershotmaster** [comment]
But can that not be removed with vanishnopacket?

**Comment by Snipershotmaster** [comment]
I ment the essentials config, i have disabled allow-silent-join-quit and it still joins me with Invisibility II.
And can this be fixed with this plugin?

**Comment by mbax** [comment]
This plugin is not Essentials, nor will it fix problems you have while still using Essentials.
