### ISSUE TITLE
 - vanish.preventoutgoingdamage Not working

### ISSUE THREAD

**Issue by ManBeastPig** [mbax/VanishNoPacket#635]
I give my players         - vanish.preventoutgoingdamage
but they can still hit others whilst in /Vanish mode.

**Comment by ManBeastPig** [comment]
R: v3.19.1 for CB 1.7.9-R0.1 Apr 26, 2014 on Spigot 1.8.8

**Comment by mbax** [comment]
> on Spigot 1.8.8

Probably a bug.
