### ISSUE TITLE
Joining

### ISSUE THREAD

**Issue by xboxhacks** [mbax/VanishNoPacket#636]
Is there a way to not going auto vanish upon joining the server?

**Comment by TheMolkaPL** [comment]
Yes, just remove the `vanish.joinvanished` permission.

**Comment by mbax** [comment]
By default you do not auto vanish upon joining. If that is happening, you have explicitly granted yourself the permission nodes to do so. Don't grant all nodes without reading the documentation! ;)

**Comment by xboxhacks** [comment]
@mbax I want to keep the * node for all owners on the server. Is there a way to remove the specific vanish.joinvanished node at all in pex?

**Comment by EvilOlaf** [comment]
You should not give `*` as permission unless you know what you are doing.
However this is not an issue with VNP, so you probably want to ask the guys of PermissionsEx for help ;)

**Comment by xboxhacks** [comment]
I think i know what im doing as im configuring my server to how i want. Personally i think there should be something in the config for it not have it as a permission node.

**Comment by TheMolkaPL** [comment]
If you are using [PermissionsEx plugin](https://github.com/PEXPlugins/PermissionsEx) just use as following:

```yml
operators:
    permissions:
    - '*'
    - '-vanish.joinvanished'
```

PEX will give you every single permission because of *. After this specified permissions will be removed from the user's permissionlist because they starts with `-` mark.

**Comment by mbax** [comment]
> I think i know what im doing as im configuring my server to how i want. Personally i think there should be something in the config for it not have it as a permission node.

If the `*` node is "how [you] want" then you want every single permissions node regardless what it means. That's just poor administration.

I think what you're *actually* looking for, @xboxhacks , is giving yourself OP. The VanishNoPacket permission nodes that you don't want are *not* given to OPs. The `*` node is like saying "I want everything that OPs get, *and* everything they don't get please" which can be dangerous. 

I like this analogy about it:

* OP is like asking for a pizza with "everything" on it and getting a delicious pizza with all the standard toppings.
* `*` is like asking for a pizza with "everything" on it and getting a pizza with standard toppings, mouse droppings, mud, cockroaches, hair, and everything else the pizza place had available to put on top of it in the shop.


As for why there isn't a config option, that would mean you'd need to enable it twice just to use it which would be silly. Permission nodes work 100% of the time and work great.
