### ISSUE TITLE
OPs get all Vanish permissions

### ISSUE THREAD

**Issue by DKing328** [mbax/VanishNoPacket#637]
Hello,

I have been using VanishNoPacket for many months, with completely no problems, up until now. We are opening a new Factions server, and decided to use the plugin on there, and we've realized that if a player has OP status on the server, the plugin is acting as if they have the node vanish.*. We use this plugin for the silent join/leave feature and because of this, Administrators join the server vanished, and sometimes if an OP'd player joins, they want to chat/build while vanished, and that is not possible when this issue is occurring. 

We have tested this with OP and non-OP players; the issue only occurs with players who have OP. If the player is non-OP, the plugin works completely fine. None of the players have the '*' permission. 

Is anyone else experiencing issues similar to this? Is there something I can do to correct the problem? 

Thank you,
_DMK_ (DKing328)

Permissions.Yml(unfinished): http://pastebin.com/x8dpnc5U
VanishNoPacket Version: 3.19.1
Spigot Version: 1.8.8

**Comment by mbax** [comment]
I really appreciate that you've put effort into testing this. :)

I know that with Bukkit/CraftBukkit this wasn't an issue; permissions behaved as expected. All but a few permission nodes are set to not-op, the explicit "don't give this to OPs" label. It's gonna be either the Spigot (the 1.8 "CraftBukkit" is also Spigot) build or your permissions plugin causing the issue.

**Comment by DKing328** [comment]
Thank you for the quick response! 
Anyway, we're using the plugin on our creative server (with the same PermissionsEx and Spigot version), and it works perfectly, so I'm not sure why it's deciding to do that. It's honestly not really a big deal (because we don't OP our Admins, only Owners). But I'll keep messing around with it and see if I can pin-point the reason why this is occurring. If I find anything out, I'll be sure to inform you!

**Comment by mbax** [comment]
Make sure you're using the absolute latest version of PEX. For **years** PEX was the number one cause of problem reports for this plugin, to the point that I wrote a several page long document about it (and still have the short URL memorized:  http://goo.gl/MHhbl ).

**Comment by EvilOlaf** [comment]
Oh my gosh :D

**Comment by DKing328** [comment]
Hey again,

So although this issue wasn't fixed, permissions-wise, I'll close this issue thread because I recently learned you can enable/disable things such as nochat with commands like /nc. Thanks again for your quick responses, and keep up the phenomenal work with the plugin! 

_DMK_ (DKing328)

**Comment by DKing328** [comment]
Okay, I happened to see the issue opened right after mine, and noticed I was using the second newest version of Multiverse. I updated Multiverse and this issue disappeared completely. Thank you for all of your help!

**Comment by mbax** [comment]
\o/
