### ISSUE TITLE
"effects disabled by default"

### ISSUE THREAD

**Issue by Annowins** [mbax/VanishNoPacket#638]
Dear M Bax,

I am trying to use your plugin vanishnopacket for my server but when I vanish (with or without op)
It automatichly gives all the effects and it should be disabled by default and it is at all files (plugin)
I even tryed removing the effects permmisions completely but it still gives the effects on my server.

I have no Idea how this is possible and I tryed alot of things many times but so far no result.
I would be blessed if you could help me.

Kind regards,

Annowins

**Comment by mbax** [comment]
If you're getting effects, you have granted yourself those perm nodes. I bet you're running PEX or GM and have granted yourself the '*' node. Don't do that unless you want EVERYTHING EVER, which you clearly don't :)

**Comment by Annowins** [comment]
I use pex but have not given myself "*" but op and I was in gamemode but I have not one single group with *


Kind regards 


Annowins



From: Matt Baxter

Sent: Friday, November 13, 01:56

Subject: Re: [VanishNoPacket] "effects disabled by default" (#638)

To: mbax/VanishNoPacket

Cc: Annowins



If you're getting effects, you have granted yourself those perm nodes. I bet you're running PEX or GM and have granted yourself the '*' node. Don't do that unless you want EVERYTHING EVER, which you clearly don't :)

**Comment by mbax** [comment]
Maybe you're using a super old version of PEX? Or the newest version has an issue.

Regardless, ask the PEX folks for help on this issue. You're getting a permission node that you didn't expect.

**Comment by EvilOlaf** [comment]
VNP with latest Pex works fine.

**Comment by mbax** [comment]
@EvilOlaf Have you tested while having OP?

**Comment by EvilOlaf** [comment]
Not yet. Hold on a sec...

**Comment by Annowins** [comment]
I have the same but the effects appear

**Comment by mbax** [comment]
OH MAN, THAT BUG.

Make sure you're on the absolute latest Multiverse. It had a hilarious bug giving OP the * node.

**Comment by Annowins** [comment]
Aaah oke I will check that right now

**Comment by Annowins** [comment]
Oke I checked and I had the 2.4 versio 2.5 version fixed everything! thank god that you helped me with this! :D

**Comment by mbax** [comment]
Woohoo!
