### ISSUE TITLE
Particles and Bats doesn't work in 1.8

### ISSUE THREAD

**Issue by Jerimu** [mbax/VanishNoPacket#639]
The Particles and the Bats doesn't work in 1.8 may there will be a fix for that?

**Comment by mbax** [comment]
If they don't work, then whatever you're using has managed to break its compatibility with the Bukkit API (which stopped development prior to 1.8)

**Comment by Jerimu** [comment]
Like spigot you mean ;p

**Comment by mbax** [comment]
If that's what you're using. I'm not going to assume that, when other systems **not** evading the DMCA takedown exist.

Either way, there's nothing wrong with the VNP code on this.
