### ISSUE TITLE
vanish.joinwithoutannounce suddenly started malfunctioning.

### ISSUE THREAD

**Issue by MithrandirCraft** [mbax/VanishNoPacket#640]
I am seeing player join messages allthough everyone has the "vanish.joinwithoutannounce" permission.

This issue emerged recently, without me even configuring VNP or PEX. I just restarted the server after making some changes on some other plugins.

I think I remember having experienced these or symilar malfunctions previously, it doesn't look like they always work 100% well.

---------------------------
VNP version: 3.19.1
Spigot version: 1.8.8

**Comment by mbax** [comment]
So... if VNP hasn't changed in a long time... this is VNP's issue how? :P

**Comment by MithrandirCraft** [comment]
What a fine way to renounce to any responsability.

Trust me, I don't report bugs without making 100% sure they are not being caused by my side.

**Comment by mbax** [comment]
I agree; it's a fine way to renounce responsibility. ^_^

Here's the [relevant](https://github.com/mbax/VanishNoPacket/blob/c1706bf43442454c5add436462af7093f5774376/src/main/java/org/kitteh/vanish/VanishPerms.java#L169-L171) [codebits](https://github.com/mbax/VanishNoPacket/blob/c1706bf43442454c5add436462af7093f5774376/src/main/java/org/kitteh/vanish/listeners/ListenPlayerJoin.java#L45-L52):

```java
if (VanishPerms.joinWithoutAnnounce(event.getPlayer())) {
    this.plugin.getManager().getAnnounceManipulator().addToDelayedAnnounce(event.getPlayer().getName());
    event.setJoinMessage(null);
    if (statusUpdate.length() != 0) {
        statusUpdate.append(" and ");
    }
    statusUpdate.append("silently");
}
// and
public static boolean joinWithoutAnnounce(Player player) {
    return player.hasPermission("vanish.joinwithoutannounce");
}
```

Event message is set to null, meaning it won't display to folks. If you have the permission node `vanish.statusupdates` then you will receive the notification there about joining silently.

If this were unreliable, I'd have far more reports. My suspicion is that you added a plugin that provides customized join messages and it's written poorly or in a way that assumes it is the most important plugin and has the final say in whether or not a join message appears.

**Comment by MithrandirCraft** [comment]
Understood. That's a nicer answer :) Thank you.

Allthough that's not the only thing that started malfunctioning recently. Players are able to see me for a short ammount of time when I log in. I'm not sure why.

I'll provably be reinstalling and re-exploring your plugin completely, as it's been there for two years now, without me touching anything lol.

**Comment by mbax** [comment]
Well, there's always the fallback answer of "Spigot probably broke it." I've had all sorts of reports from folks running their stuff over the last year, all caused by them.

Looking forward to more plugins being available on [Sponge](http://spongepowered.org)
