### ISSUE TITLE
Wrongly tagged release on dev.bukkit

### ISSUE THREAD

**Issue by rlf** [mbax/VanishNoPacket#644]
v3.20 wrongly tagged as 1.7.9, text says "won't work with 1.7.9 and earlier".
http://dev.bukkit.org/bukkit-plugins/vanish/files/86-v3-20/

Thought you might want to know, before the kids start complaining...

**Comment by mbax** [comment]
There is no 1.7.10-R0.1-SNAPSHOT tag, as they only tagged releases (beta, rb)

**Comment by rlf** [comment]
Ah, ok, I assumed it was a 1.8 release, and not a 1.7.10 - my bad.

**Comment by mbax** [comment]
VNP supports Bukkit builds. We (Bukkit) never published anything for 1.8 or beyond.
