### ISSUE TITLE
VPN: messages.yml? (Feature Request)

### ISSUE THREAD

**Issue by Chalwk77** [mbax/VanishNoPacket#645]
Feature Request:

* messages.yml ?

Any chance of adding some method to modify in-game messages?

**Comment by mbax** [comment]
That is absolutely a feature to be added to 4.0, which is available on a separate repo: https://github.com/KittehOrg/Vanish

**Comment by Chalwk77** [comment]
Will this be available on the bukkit version?

**Comment by mbax** [comment]
Bukkit died in August 2014. Hurray future.

**Comment by Chalwk77** [comment]
Fair enough. Well I would like to hold in high esteem an opportunity to say thanks for your dedication, time and effort put into this plugin thus far. Many thanks.

**Comment by mbax** [comment]
Thank you for the kind words. :)

I look forward to more of the community migrating to Sponge as it becomes more and more obvious as a better solution for plugins going forward.
