### ISSUE TITLE
Libsdisguises and vanishnopacket

### ISSUE THREAD

**Issue by KanjiOkami** [mbax/VanishNoPacket#647]
Is it possible to have the disguise take priority over vanishnopacket? With disguisecraft we were able to disguise without unvanishing but with that plugin barely working and having more interest in some of the other features libsdisguises has we tried switching over only to find out we have to unvanish to have the disguise be seen. Is there a way to change that?

We also tried libsdisguisecraft to no avail.

**Comment by mbax** [comment]
I... have no idea! I can definitely look into better support for 4.0, but that's over on this repo: https://github.com/KittehOrg/Vanish
