### ISSUE TITLE
Players can hear sound when hitting s.o. vanished

### ISSUE THREAD

**Issue by minoneer** [mbax/VanishNoPacket#648]
When I am vanished and hit another player, that player can hear the hitting sound.

Versions:
server: Paper git-Paper-612 (MC: 1.9)
VanishNoPacket: 3.20

**Comment by mbax** [comment]
Report bug to Paperfolk, assuming that you are telling VNP to block damage-out

**Comment by minoneer** [comment]
Thanks for the quick reply. What exactly do you mean by "telling VNP to block damage-out"? I am unable to find a corresponding config option. Or did I miss something?

**Comment by TheMolkaPL** [comment]
This the Spigot, not the VanishNoPacket issue. This is the Spigot Teams objective to *properly* implement Bukkit (which is the Minecraft server API that VPN uses).

**Comment by mbax** [comment]
Not Spigot, @TheMolkaPL, but Paper ;)

@minoneer its a toggleable feature, see the documentation.
