### ISSUE TITLE
Vanish indicator

### ISSUE THREAD

**Issue by Defnder** [mbax/VanishNoPacket#649]
Just a little feature suggestion/request for your fantastic plugin:

It would be great, to have an indicator, if you are vanished.
I'm thinking about something like the new status effect indicator (1.9). There is already an indicator for the invisibility effect, which is quite obsolete, when using vanish. Maybe there is a way to show this indicator all the time you are vanished.

**Comment by TheMolkaPL** [comment]
[Bukkit](https://github.com/Bukkit/Bukkit) is not updated to 1.9.

Also @mbax (VNPs author) is not contributing to this project due Mojangs did not clarified the position of Minecraft modding.

> 1) Mojang has not clarified their position on the legality of Bukkit and modding. While they publicly stated on twitter that Bukkit has a 'special relationship' they very clearly denied that same relationship in the letter they sent Wolvereness which he quotes in his DMCA takedown. Their COO made several statements about the project which did not match up with reality, which is scary. I do not feel safe continuing work on Bukkit plugins until Mojang makes it explicitly clear that it's safe.

> 2) There has not been and will never be a 1.8 release of Bukkit or CraftBukkit. The only major Bukkit fork legally updated to 1.8 is Glowstone, which still lacks a lot of features so isn't yet worth updating to even if the first item in this list were resolved. The other updated fork is Spigot, which I refuse to support. Here's a short list of examples why:

> They spent substantial time insulting me and my fellow Bukkit developers
The founder, md_5, regularly attacked me directly, out of some one-sided feud he created (example)
They spent a lot of time trying to convince the community they were doing the hard work of a Bukkit update, when they were just applying some patches on top of my hard work.
They convinced the community to pay them a huge pile of money to fight the DMCA takedown they received, only to never actually file the counterclaim they said they would do.
They are now ignoring the (apparently determined by the lawyers they paid to be valid, as they didn't issue a response) DMCA takedown, hiding their servers behind proxies.

https://github.com/mbax/VanishNoPacket/issues/627
