### ISSUE TITLE
Permanently disable effects

### ISSUE THREAD

**Issue by AlHollandiyah** [mbax/VanishNoPacket#650]
I would like to request a way to permanently disable effects. I tried toggling them before unvanishing, but next time I log in they are on again. Ideally there would be an option in the config like the ones for force announcement, where you could set effects to true or false. Is that possible? Our server is running on spigot 1.8.7! Many thanks!

**Comment by mbax** [comment]
Howdy!

Effects are disabled by default. The **only** way to have the effects happen is to explicitly grant the permission nodes for them. So, the easy solution is to just... not grant the nodes you're currently granting. :)

**Comment by AlHollandiyah** [comment]
I tried negating them before giving the OP rank vanish.* but that didn't work. Is there any way other then posting a whole list of permissions minus the effects? Because now it's just 1 line, and thats more efficient.

**Comment by mbax** [comment]
If you don't want all the permissions in VNP, don't grant vanish.*

Grant the nodes you want. There are several larger nodes granting things less than everything but more than one-by-one. See the documentation for details.
