### ISSUE TITLE
Default Toggles

### ISSUE THREAD

**Issue by JumanjiCraft** [mbax/VanishNoPacket#653]
Every time my staff join the server, they need to toggle chat and no interact. How can I change this so that it is default toggle disabled?

Thanks!

**Comment by mbax** [comment]
Do you mean you need no-chat enabled, or no-chat disabled?

**Comment by mbax** [comment]
I suppose I can answer both sides:

"Help my staff are chatting while vanished, and need to toggle it so they don't!"
Give them the permission nodes.

"Help my staff can't chat while vanished!"
Stop giving them those permission nodes.

Nodes: https://dev.bukkit.org/bukkit-plugins/vanish/pages/permissions/

**Comment by JumanjiCraft** [comment]
This actually didn't help me. I gave myself negative perms for toggling. I can no longer toggle no interact or no chat. That would be fine except I can't chat when I'm vanished. 


What I was asking is how can I set it so that when a player with vanish logs in, (op especially), that their default state is to have no-interact disabled? Because this solution didn't work. 

When I log in I want to be vanished but be able to chat. I am not able to do that.

**Comment by JumanjiCraft** [comment]
Duh, I'm a moron. I was disabling the ability to toggle not the actual nodes for nochat/nointeract etc. 

Sorry.

**Comment by mbax** [comment]
Judging by your "negative permissions" statement I'm going to assume you're using wildcards (`*`). 

Don't.

Grant only the nodes you want. There are half a dozen surprise features in VNP granted as a result of granting more than you want. And there are plenty of other plugins with surprises that way too.
