### ISSUE TITLE
Vanish bug afflicting players

### ISSUE THREAD

**Issue by afroman84** [mbax/VanishNoPacket#654]
Hello, I'm using latest version of VanishNoPacket, latest version of EssentialsX, latest version of Bungeecord and latest of paperclip.jar. 
In one server of my network there's a breaking-server bug, players can't see who joined after them. 
They are visible in the tablist, but can't tab-complete their nicknames.
I activated the debug mode both in VNP and EssentialsX, i removed all others plugins who may interfere with visibility status. 
This is what i find in the console when a player joins:
http://pastebin.com/7tyYPQk7
Apparently no errors in server logs and also in bungee logs. 
I'm really going crazy for this. I don't even know if this depends on VanishNoPackets or EssentialsX.
Please help :(

**Comment by mbax** [comment]
Remove VNP, restart server, test for problem.

**Comment by afroman84** [comment]
It were another plugin (RadarJammer). Thank you for listening me, I were one foot from madness, sorry :P

**Comment by mbax** [comment]
Madness gets to all of us, eventually :3
