### ISSUE TITLE
Open shulker boxes "silently" like normal chests? 

### ISSUE THREAD

**Issue by Sandukhan** [mbax/VanishNoPacket#658]
I was wondering if vanish could handle shulker boxes like normal chests, so that you can open them silently without the need of toggle nointeract. Right now its not possible to look into them silently.

Running VanishNoPacket version 3.20 on spigot 1.11.2

**Comment by TheMolkaPL** [comment]
We can't block shulker boxes because [Bukkit](https://github.com/Bukkit/Bukkit) doesn't support them (and I'm not talking about its forks like [Spigot](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse)).

**Comment by mbax** [comment]
(what @TheMolkaPL said)
