### ISSUE TITLE
Vanished players cannot take damage from players

### ISSUE THREAD

**Issue by jearnold52** [mbax/VanishNoPacket#661]
Is there a way to cause vanished players to still take damage if another player hits them?

**Comment by TheMolkaPL** [comment]
Yes, use the `vanish.preventincomingdamage` permission.

**Comment by jearnold52** [comment]
I think I was maybe a bit vague about what I meant.

**Example:** I vanish myself. I have toggled off damage-in and damage-out(so that "damage prevention" is turned off), so I should, theoretically, be able to take damage. However, when I /vanish myself, and another player tries to hit me while vanished, no damage is dealt.

Below is the link to my PEX file:
PEX permissions.yml - https://hastebin.com/ugozozuzej.vbs

**Comment by mbax** [comment]
The client trying to attack you doesn't know you exist, so it can't tell the server it's hitting you, so the server can't decide to cause damage.
