### ISSUE TITLE
I have invisibility when I join and it does not go away.

### ISSUE THREAD

**Issue by Tituss77** [mbax/VanishNoPacket#664]

**Comment by TheMolkaPL** [comment]
https://github.com/mbax/VanishNoPacket/blob/6d8d91c1aad959dc16fb585cbf5467a37d7bec39/src/main/resources/plugin.yml#L71-L73

You have this permission - revoke it please.

**Comment by Tituss77** [comment]
Thank you

**Comment by mbax** [comment]
Read the documentation before giving yourself permission nodes!
