### ISSUE TITLE
Vanish Permissions

### ISSUE THREAD

**Issue by broyuken** [mbax/VanishNoPacket#666]
I'm trying to set up vanish so that I can choose what effects/toggles I want, and have it actually remember them but it seems to be a giant pain to do. All I want is to be able to give damage out, none in, and no effects by default.

This is my config:
    - vanish.silentjoin
    - -vanish.preventoutgoingdamage
    - -vanish.effects.*
    - vanish.*

When I log in, I have ALL effects and ALL toggles turned on. The negating doesn't look like it's working at all. How can I fix this besides removing vanish.* and granting everything else manually?

**Comment by Deaygo** [comment]
You might want to try adding vanish.* before the negations and see if that works.

**Comment by broyuken** [comment]
It didn't work, and according to the documentation for PEX (my permissions manager) it reads top down, so that would also give all permissions.

**Comment by Deaygo** [comment]
Did you remove it from the bottom when adding it to the top of the list?  It would read it top down meaning that it would remove the permissions for vanish.preventoutgoingdamage, but then you are granting vanish.* at the bottom which would give the permissions back.

Try this:

- vanish.*
- vanish.silentjoin
- -vanish.preventoutgoingdamage
- -vanish.effects.*

**Comment by broyuken** [comment]
I figured it out, once it finds a permission it stops looking for it with pex. The issue I ran into was that vanish.standard was above that all which gave the vanish.preventdamage permission before it was negated. This caused it to not be negated at all. I think I'm good now, thanks!

**Comment by mbax** [comment]
Much easier to only grant the ones you want (typically using `vanish.standard` as a starting point with a pile of them, but I'm glad you have it working the way you want! :)
