### ISSUE TITLE
Global tab-complete shows vanished players...

### ISSUE THREAD

**Issue by pozzzzy** [mbax/VanishNoPacket#671]
I am running a 1.8.9 Spigot server with VanishNoPacket v3.20.1, however, when regular players use tab to auto-complete names, it includes vanished players as well.
The whole player base now knows of this bug and are using it to see if there are any vanished players online.

Is there a work-around or fix for this that does not involve disabling global tab-complete?

**Comment by mbax** [comment]
When you say "global" tab complete, are you talking about within a single server or some sort of multi-server setup?

If one server, we're talking about a bug in Spigot.

If multiple servers (bungeecord?) it's a bug with whatever else is providing that.

sorry! :(

**Comment by pozzzzy** [comment]
bungeecord, yes.
thanks tho
