### ISSUE TITLE
Phantoms will spawn above vanished players

### ISSUE THREAD

**Issue by C4K3** [mbax/VanishNoPacket#675]
Phantom spawning does not work like other mob spawning, but rather phantoms spawn targeting a specific player.

If a player is vanished, that player will still spawn phantoms. If other players nearby know they have slept and therefore cannot have spawned the phantoms, they can conclude that there must be a vanished player nearby.

This violates the assumptions of nointeract. I propose that if nointeract is enabled for a player, then that player will not spawn phantoms.

**Comment by mbax** [comment]
Phantoms don't exist in Bukkit's API, as Phantoms came out I believe years after the last Bukkit release. Sorry! :(
