### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by LtHammerman** [mbax/VanishNoPacket#678]
VanishNoPacket doesn't work on my server.  When I try /vanish, i get this message:

/vanish
/v [player] [on:off]

I'm running 1.12.2 version of minecraft on my server.

**Comment by mbax** [comment]
Thaaaaaaat doesn't sound like VNP's messages at all. Please do this:

1) Stop your server.
2) Start your server, and watch the console until it gets to "Done"
3) Stop your server.
4) Copy the entire contents of the file `logs/latest.log` to https://gist.github.com/ and then link it here.
  * Remove any IP addresses or other sensitive details before clicking paste.

**Comment by LtHammerman** [comment]
Thanks, here is the link https://gist.github.com/LtHammerman/a43731aa441d1d3f2bd04dbc9b6b7f65

**Comment by mbax** [comment]
Try one version of VNP earlier than the one you have.

**Comment by LtHammerman** [comment]
Thanks very much, it's all working now.

**Comment by mbax** [comment]
Woohoo!
