### ISSUE TITLE
Effects don't keep when player leaves

### ISSUE THREAD

**Issue by NPCtom** [mbax/VanishNoPacket#679]
If I remove the Explode & Lightning effect and leave the server next time I go back on i still have all of the effects. Anyway to prevent this?

**Comment by mbax** [comment]
How are you removing it?

**Comment by NPCtom** [comment]
@mbax using /vanish effects

**Comment by mbax** [comment]
If you are getting that every time you join, then you have *granted yourself the permission node* for it. This is a sign that your permissions related to this plugin are *completely messed up*.

What is your current list of perms you grant yourself for VNP?

**Comment by NPCtom** [comment]
Permission | Value | Expiry | Server | World | Contexts |  
-- | -- | -- | -- | -- | -- | --
worldedit.* | true | never | global | global | none | deletecontent_copy
* | true | never | global | global | none | deletecontent_copy
*.worldedit | true | never | global | global | none | deletecontent_copy
BanHammer.execute | true | never | global | global | none | deletecontent_copy
ab.ban.exempt | true | never | global | global | none | deletecontent_copy
ab.ban.notify | true | never | global | global | none | deletecontent_copy
ab.ban.perma | true | never | global | global | none | deletecontent_copy
ab.ban.temp | true | never | global | global | none | deletecontent_copy
ab.banlist | true | never | global | global | none | deletecontent_copy
ab.changeReason | true | never | global | global | none | deletecontent_copy
ab.check | true | never | global | global | none | deletecontent_copy
ab.check.ip | true | never | global | global | none | deletecontent_copy
ab.history | true | never | global | global | none | deletecontent_copy
ab.ipban.exempt | true | never | global | global | none | deletecontent_copy
ab.ipban.notify | true | never | global | global | none | deletecontent_copy
ab.ipban.perma | true | never | global | global | none | deletecontent_copy
ab.ipban.temp | true | never | global | global | none | deletecontent_copy
ab.kick.exempt | true | never | global | global | none | deletecontent_copy
ab.kick.notify | true | never | global | global | none | deletecontent_copy
ab.kick.use | true | never | global | global | none | deletecontent_copy
ab.mute.exempt | true | never | global | global | none | deletecontent_copy
ab.mute.notify | true | never | global | global | none | deletecontent_copy
ab.mute.perma | true | never | global | global | none | deletecontent_copy
ab.mute.temp | true | never | global | global | none | deletecontent_copy
ab.mute.undo | true | never | global | global | none | deletecontent_copy
ab.tempban.exempt | true | never | global | global | none | deletecontent_copy
ab.tempban.notify | true | never | global | global | none | deletecontent_copy
ab.tempipban.exempt | true | never | global | global | none | deletecontent_copy
ab.tempipban.notify | true | never | global | global | none | deletecontent_copy
ab.tempmute.exempt | true | never | global | global | none | deletecontent_copy
ab.tempmute.notify | true | never | global | global | none | deletecontent_copy
ab.tempwarn.exempt | true | never | global | global | none | deletecontent_copy
ab.tempwarn.notify | true | never | global | global | none | deletecontent_copy
ab.warn.exempt | true | never | global | global | none | deletecontent_copy
ab.warn.notify | true | never | global | global | none | deletecontent_copy
ab.warn.perma | true | never | global | global | none | deletecontent_copy
ab.warn.temp | true | never | global | global | none | deletecontent_copy
ab.warn.undo | true | never | global | global | none | deletecontent_copy
ab.warns.other | true | never | global | global | none | deletecontent_copy
essentials.chat.spy | true | never | global | global | none | deletecontent_copy
group.admin | true | never | global | global | none | deletecontent_copy
meta.default.false | true | never | global | global | none | deletecontent_copy
prefix.5.&5[Developer]&4 | true | never | global | global | none | deletecontent_copy
prefix.5.&d[Admin]&4 | false | never | global | global | none | deletecontent_copy
vanish.effects.bats | true | never | global | global | none | deletecontent_copy
vanish.effects.flames | true | never | global | global | none | deletecontent_copy
vanish.effects.smoke | true | never | global | global | none | deletecontent_copy
vanish.vanish.off | true | never | global | global | none | deletecontent_copy
vanish.vanish.on | true | never | global | global | none | deletecontent_copy
weight.10 | true | never | global | global | none | deletecontent_copy

**Comment by NPCtom** [comment]
vanish.effects.bats | true | never | global | global | none | deletecontent_copy
vanish.effects.flames | true | never | global | global | none | deletecontent_copy
vanish.effects.smoke | true | never | global | global | none | deletecontent_copy
vanish.vanish.off | true | never | global | global | none | deletecontent_copy
vanish.vanish.on | true | never | global | global | none | deletecontent_copy
