### ISSUE TITLE
Issues with silent chest

### ISSUE THREAD

**Issue by aescraftbr** [mbax/VanishNoPacket#681]
Hello,
I know this is not updated, but I need some help.

I gave myself only the perm "vanish.vanish", and when i'm not vanished, the chests are opened silently. 

Even with the perm "vanish.toggle.chests" and the silent chest disabled, it stills open silenced. 

I'm doing something wrong?

spigot 1.14.4

**Comment by mikroskeem** [comment]
More information needed - what plugins do you have installed? How does the message look like?

Just to rule out that VNP doesn't do this.
