### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by julianborghuis** [mbax/VanishNoPacket#682]
Hello,

For my plugin i need Vanish No Packet. But i cant compile it i get this error
[ERROR] Failed to execute goal on project KDF: Could not resolve dependencies for project nl.dusdavidgames:KDF:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.kitteh:VanishNoPacket:jar:3.9 -> org.getspout:spoutplugin:jar:dev-SNAPSHOT: Failed to read artifact descriptor for org.getspout:spoutplugin:jar:dev-SNAPSHOT: Could not transfer artifact org.getspout:spoutplugin:pom:dev-SNAPSHOT from/to bukkit-repo (http://repo.bukkit.org/content/groups/public): repo.bukkit.org: Unknown host repo.bukkit.org -> [Help 1]

what to do?

**Comment by mbax** [comment]
How about just building against the existing compiled jar from BukkitDev?

**Comment by mbax** [comment]
Closing due to lack of response
