### ISSUE TITLE
Can set off raids while vanished

### ISSUE THREAD

**Issue by haykam821** [mbax/VanishNoPacket#683]
No matter what flags I have toggled, going into a village while vanished, not in spectator mode, and with the Bad Omen effect will cause a raid to start. This is not useful as people will be alerted to the raid.

**Comment by TheMolkaPL** [comment]
Versions newer than 1.7.10 aren't supported.

**Comment by ZandercraftGames** [comment]
For what reason?

**Comment by TheMolkaPL** [comment]
Mojang isn't clear on their position on modding the game.

**Comment by ZandercraftGames** [comment]
Uhm. How so? I think they have been quite clear recently that they support and endorse it. Especially with their Minecon Live segments.

**Comment by ZandercraftGames** [comment]
> Mojang isn't clear on their position on modding the game.

I also might add that creating plugins for server software to enhance moderation abilities could hardly be considered modding the base-game. Its not like you are directly making changes to the game's jar file.
