### ISSUE TITLE
DiscordSRV Fake Join/Quit Integration

### ISSUE THREAD

**Issue by Dinty1** [mbax/VanishNoPacket#686]
DiscordSRV recently added a feature to allow fake join messages from vanish plugins. Not sure if this plugin is still maintained but it would be a useful feature to have.

[You can read more about the feature here](https://github.com/DiscordSRV/DiscordSRV/issues/220)

**Comment by DB8888** [comment]
Alternatively, a fakejoin and fakequit event could be used by DiscordSRV's alerts feature :)

**Comment by Dinty1** [comment]
Pull request opened.
