### ISSUE TITLE
remove command in tab-complete all users

### ISSUE THREAD

**Issue by FazziCLAY** [mbax/VanishNoPacket#690]
please make it so that the player does not have the team in the tab-complete if he does not have rights to it 

ps English is not my native language, I apologize if I write awkwardly

**Comment by mbax** [comment]
I think I can make this happen...

**Comment by mbax** [comment]
Should be resolved in latest commit, future release.

**Comment by mbax** [comment]
https://github.com/mbax/VanishNoPacket/commit/a6290337efe5c270ff4090beadaf8c079d6e4fcd#diff-98201effe40eaf4a0e8826fadd6c5c9d5beaf9d737226b514f0853f44987a67fR15
