### ISSUE TITLE
Barrels have to be opened silently!

### ISSUE THREAD

**Issue by ChrissW-R1** [mbax/VanishNoPacket#691]
As a vanished player, I want to open barrels like chests (without been discovered by other users).

Now, if I open a chest no sound is played and the animation of the chest opening is blocked. I get only an message in the chat from the plugin. Barrels are not blocked, so if I look into a barrel all other (non-vanished) users around hear the sound of the barrel and could see the opened barrel. So I could discovered by barrels.

**Comment by Dinty1** [comment]
And shulkers actually

**Comment by mbax** [comment]
Should be resolved for next release. :)
