### ISSUE TITLE
HTTP Maven Repos

### ISSUE THREAD

**Issue by Kas-tle** [mbax/VanishNoPacket#703]
Hello,

Same minor issue I opened on the PlayerVaults repo; just some links that should be HTTPS in the pom.

https://github.com/mbax/VanishNoPacket/blob/959b55931b3cb6969a5872fbb8a09c3720e2e50c/pom.xml#L44
https://github.com/mbax/VanishNoPacket/blob/959b55931b3cb6969a5872fbb8a09c3720e2e50c/pom.xml#L48

**Comment by mbax** [comment]
Finally resolved. :)
