### ISSUE TITLE
Database support (MySQL/MariaDB)

### ISSUE THREAD

**Issue by ReferTV** [mbax/VanishNoPacket#708]

**Comment by mbax** [comment]
For... what?

**Comment by mbax** [comment]
![image](https://user-images.githubusercontent.com/181668/155417621-0ec33904-c01c-4e8d-bc06-1ef7449a647b.png)

@ReferTV but seriously what would database support for this plugin even *do*?

**Comment by ReferTV** [comment]
> ![image](https://user-images.githubusercontent.com/181668/155417621-0ec33904-c01c-4e8d-bc06-1ef7449a647b.png)
> 
> @ReferTV but seriously what would database support for this plugin even *do*?

For example, if an admin turned on vanish in a lobby and then switched to another mode, the vanish would stay on.

**Comment by mbax** [comment]
I'm deciding that this is not a change I will be pursuing. It could be nearly executed properly with a plugin on the proxy that tracks (via this plugin's plugin messaging support) vanish status, and unvanishes users on joining new servers (default to join vanished).
