### ISSUE TITLE
1.19 Support

### ISSUE THREAD

**Issue by lokka30** [mbax/VanishNoPacket#719]
Hi mbax! Does VanishNoPacket have compatibility and support for 1.19 servers?

I can't believe VanishNoPacket is still going to this day, thank you for maintaining it. :)

**Comment by mbax** [comment]
I've been traveling! It *should* support 1.19 just fine, though I'll be looking to work on updates this week for various plugins.

**Comment by lokka30** [comment]
Cheers legend! (I wish I could help, I'm useless with packets. 🤦🏻)
