### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by SaumyaKhobragade** [mbax/VanishNoPacket#722]
When you run /vanish fakequit or /vanish fakejoin, it gives the error access denied.

**Comment by Dinty1** [comment]
http://dev.bukkit.org/projects/vanish/pages/permissions Make sure you’ve given yourself the correct permissions

**Comment by SaumyaKhobragade** [comment]
Well, I have all the permissions, I am the operator @Dinty1.

**Comment by Dinty1** [comment]
Are you using a permission plugin?

**Comment by SaumyaKhobragade** [comment]
No I am not using a permission plugin, I have Geyser, VanishNoPacket. Floodgate, DiscordSRV, ViaVersion, GriefPrevention, ProtocolLib, LoginSecurity, Openinv And PluginHider lastly.

**Comment by mbax** [comment]
VanishNoPacket doesn't grant literally every permission node to ops. 

Grab yourself LuckPerms and grant the permission nodes you want yourself to have according to the documentation! 😄
