### ISSUE TITLE
Same issue as others with deprecated performance?

### ISSUE THREAD

**Issue by ThermicPumaa** [mbax/VanishNoPacket#726]
02.04 22:28:11 [Server] [WARN] [VanishNoPacket] "VanishNoPacket v3.22" has registered a listener for com.destroystokyo.paper.event.entity.ProjectileCollideEvent on method "public void org.kitteh.vanish.listeners.ListenPaper.onProjectileCollide(com.destroystokyo.paper.event.entity.ProjectileCollideEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [mbaxter].

not sure exactly whats going wrong here

**Comment by mbax** [comment]
There's no performance risks with this right now. It will be resolved. Thank you! :)
